### ISSUE TITLE
Coluna errada?

### ISSUE THREAD

**Issue by Eduardomb22** [faio/rfb-cnpj#1]
Prezado, bom dia. Realizei o filtro com seu arquivo, mas observei alguns erros.
Por exemplo, os IDs: 27315744 e 42103034 estão com o código do Município no DDD_1, isso acabou afetando o restante das informações da linha.

Você poderia verificar se esse erro é nos arquivos da receita ou no seu sistema?

EDIT: **Várias linhas estão com este problema.**

**Comment by faio** [comment]
Bom dia! Esses erros vem da base da receita, não só esse como vários outros campos são inconsistentes, por exemplo, tem CEP inválido, municípios que não estão na tabela município e vários outros campos, esse é um dos motivos que eu não coloquei os tipos de campos exatamente como está no manual, pois, quem for utilizar o campo (informação) faz uma pré analise e verifica e em seguida toma a decisão do que fazer com aquele campo.

Aqui temos um regra, usamos apenas os dados que vemos que são consistentes, esses dados como ddd inválido e cep nós apenas ignoramos, caso veja algum campo que está inconsistente e tenha alguma solução para o tratamento do mesmo aceitamos PR :).

**OBS: inconsistência como essa deis da minha primeira base que eu utilizei da receita sempre existem. Só muda a cada atualização deles qual é o novo valor que gerara inconsistência.**

**Comment by faio** [comment]
Outra observação, olhei hoje que uma nova versão foi postada da base, pode ser que esses problemas tenham sido corrigido na atualização deles ou novos foram adicionados.

**Comment by simoyama2** [comment]
Amigo, poderia me ajudar? Como eu faria para extrair os dados separados por UF ou cidade em CSV?

**Comment by danillorocha10** [comment]
ola @simoyama2 para tal sugiro utilização de alguma plataforma já com dados tratados como EMPRESAQUI, FACILDATA, ECONODATA, EMPRESOMETRO...

**Comment by faio** [comment]
> Amigo, poderia me ajudar? Como eu faria para extrair os dados separados por UF ou cidade em CSV?

Bom dia @simoyama2 ! Os arquivos originalmente disponibilizados pela receita já são compatíveis com o formato CSV, se você abrir eles no excell consegue fazer esse trabalho; vai ser mais honeroso pois precisa ser arquivo por arquivo.
O objetivo desse projeto não é te dar essa funcionalidade, apesar de ser bem possível fazer isso após o resultado final da execução desses scripts utilizando funções do banco de dados, porém, aparentemente você não possuí conhecimento técnico para o mesmo, recomento seguir a sugestão do @danillorocha10 que irá te poupar bastante trabalho.

Agora, se quiser tentar por si próprio, o postgreSQL tem uma função bem interessante que te permite fazer isso, você vai rodar o sistema gravando em um banco postgreSQL, posteriormente faz uma consulta SQL filtrando da forma que você deseja e joga o seu resultado em um arquivo CSV, um ponto inicial para conseguir essas informações pode ser por aqui https://www.postgresql.org/docs/9.2/sql-copy.html outras ferramentas podem te dar isso pronto ou outros bancos de dados, mais de toda forma irá precisar de conhecimento técnico para executar os mesmos.

**Comment by simoyama2** [comment]
Obrigado @faio e @danillorocha10
