### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [faio/rfb-cnpj#14]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by faio** [comment]
Olá! Está sim

**Comment by ghost** [comment]
Oi faio.

> Olá! Está sim

fico feliz pela resposta. vou ajudar como eu posso esse projeto. vou fechar essa issue, obrigado por esclarecer minha dúvida.
