### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by renatoos1** [faio/rfb-cnpj#3]
Caro Flávyo,
Parabéns pelo projeto.
Tenho uma dúvida, como eu defino a conversão para o PostgreSQL?
Obrigado!

**Comment by faio** [comment]
Obrigado @renatoos1 !

Para alterar o banco de dados passe o parâmetro --database_url utilizando o padrão SQLAlchemy, o mesmo pode ser visto no site da documentação oficial.

Para o postgres usando o conector psycopg2 você pode seguir o exemplo da documentação em: https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.psycopg2

Existe outros conectores que podem ser usados, escolha uma da sua preferencia.

OBS: não se esqueça de instalar a biblioteca do banco de dados antes e a conversão para o banco PostgreSQL é mais demorada, aqui demorou entre 12 e 14 horas.

**Comment by renatoos1** [comment]
@faio , obrigado pela resposta!!!
