### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by slmfgabriel** [faio/rfb-cnpj#4]
Boa tarde!!
Parece ser muito bom este sistema, baixei aqui mas estou com dificuldade para rodar pois não tenho muita familiaridade com Py.
Poderia disponibilizar um tutorial mais detalhado do passo-a-passo para configuração da ferramenta?
Fiz a instalação do Py, Postgree, Click e SQLAlchemy.. como faço a configuração com o banco? quais mais configurações devo me atentar?
Por favor.

Grato.
Fernando

**Comment by juanfariasdev** [comment]
o tutorial já está bem explicado.
Vou tentar do meu jeito:
depois de instalar o python e configurar ele para funcionar no terminal(vê no youtube pois não sei explicar certinho)

abre o cmd ou o powershell na pasta que está a ferramenta e dá um pip install -r requirements.txt
assim ele irá instalar tudo que precisa pro programa funcionar

termnando a instalação usa o python main.py --database_url sqlite:///db.sqlite3
a url tem que ser de acordo com o seu postgree para funcionar

**Comment by slmfgabriel** [comment]
Legal consegui fazer a importação dos dados para o Postgres.
Tenho mais duas dúvidas..
O que seria fazer em Thread?
e quanto ao relacionamento das tabelas (empresas & estabelecimentos) qual seria os ID's? CNPJ?
na tabela de empresas só aparece parte do cnpj.. não contém o dv e ordem igual da estabelecimentos

**Comment by juanfariasdev** [comment]
thread seria uma forma de usar mais processador para ficar mais rápido a instalação.

não possui relação direta, é só usando o cnpj presente na tabela. Apra conseguir consultar, terá que entender um pouco de sql para conseguir juntar tabelas com o mesmo cnpj (pra facilitar, procura como usar o inner join no postgres)
