### ISSUE TITLE
Atualização?

### ISSUE THREAD

**Issue by simoyama2** [faio/rfb-cnpj#6]
Olá
Eu rodei o script agora, mas ele baixou um arquivo SQlite do mesmo tamanho da base que  havia em maio. Os dados estão iguais aos daquela época. O site da RFB diz que houve atualização em setembro, mas eu vejo que as últimas empresas da base baixada foram abertas em maio. É algo no script ou a própria base da RFB que não foi atualizada?

**Comment by faio** [comment]
Olá, alguma coisa você fez errado, o script não armazena nenhuma informação e nem gera informação nova, talvez tenha gerado algum erro no script na hora de executar e você não viu, ou você está olhando a base errada. Pode ser também problema com a RFB, mais acho pouco provável.

**Comment by simoyama2** [comment]
Não deu nenhum erro ao rodar o script.  Executei ele em maio e agora rodei novamente com um output diferente, mas a base é exatamente a mesma.  Alguém rodou o script com essa atualização setembro pra confirmar se está de fato atualizada?
