### ISSUE TITLE
Erro ao gravar no banco de dados

### ISSUE THREAD

**Issue by simoyama2** [faio/rfb-cnpj#7]
Alguém sabe como posso resolver este erro ?

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO empresas (cnpj, razao, natureza, qualificacao_pf, capital, porte) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (('41516438', 'JHULIA KELLY VIANA SILVA 04021383255', 2135, 50, 3500.0, 1), ('41516439', 'MARCO MACHADO 36486337087', 2135, 50, 1000.0, 1), ('41516440', 'FIDELIS MATHEUS ARQUITETURA E SERVICOS LTDA', 2062, 49, 2000.0, 1), ('41516441', 'VANIA NOGUEIRA DE CARVALHO SANTOS 77448979949', 2135, 50, 2000.0, 1), ('41516442', 'LUCAS CARVALHO DOS SANTOS 26847425881', 2135, 50, 1000.0, 1), ('41516443', 'GILMAR FRANCISCO DE FARIAS 70817987487', 2135, 50, 20000.0, 1), ('41516444', 'IRLANDA MARIA SILVA RIBEIRO', 2135, 50, 0.0, 5), ('41516445', 'MARIA CRISTINA FERREIRA JULIAO PESSOA 06374428900', 2135, 50, 5000.0, 1)  ... displaying 10 of 6394 total bound parameter sets ...  ('41522842', 'MAURICIO MIZERANI DE OLIVEIRA CAMPOS 90249763672', 2135, 50, 1000.0, 1), ('41522843', 'BUSINESS FIT SERVICOS SOCIEDADE UNIPESSOAL LTDA', 2062, 49, 1000.0, 1))]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by faio** [comment]
SQLite você não pode rodar ele em processo em lote, da uma olhada se está ativado.

**Comment by simoyama2** [comment]
está desativado
