### ISSUE TITLE
Acrescenta mais informacoes no codigo

### ISSUE THREAD

**Issue by masterCredd** [faio/rfb-cnpj#8]
olá, eu estou tendo uma grande dificuldade em unir as tabelas com chave estrangeira e formar a saída do banco dedos depois que faça a mesclagem das informações você consegue me ajudar a melhorar o código tirando algumas dúvidas minhas,por favor

**Comment by masterCredd** [comment]
Estou tentando problemas na hora de baixar os arquivos

**Comment by faio** [comment]
Qual problema?

**Comment by masterCredd** [comment]
na parte de gravacao dos dados esta tendo perde de pacote  
e teria alguma forma de deixar esse download mais rapidamente?
usando uma pool?
fazendo uma relação as tablas também

**Comment by masterCredd** [comment]
e teria alguma forma de deixar esse download mais rapidamente?

**Comment by faio** [comment]
O projeto é livre para ser modificado, se você tiver uma solução melhor está aberto a receber novas alterações

**Comment by moisesrms** [comment]
@masterCredd minha sugestão é, use um gerenciador de downloads para baixar os arquivos, eles se encontram nesse endereço 

http://200.152.38.155/CNPJ/

depois de baixa-los, use os parâmetros para indicar que não quer fazer o download e aponte para o diretório onde estão os arquivos

python main.py --baixar false --diretorio_arquivos '/lugar_onde_fez_o_download' .....
